// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_event_uic_IO_clicked(lv_event_t * e); // name: I/O
extern void ui_event_uic_cd_clicked(lv_event_t * e); // name: CD
extern void ui_event_uic_md_clicked(lv_event_t * e); // name: MD
extern void ui_event_uic_fn_clicked(lv_event_t * e); // name: Function
extern void ui_event_uic_slp_clicked(lv_event_t * e); // name: Sleep
extern void ui_event_uic_stby_clicked(lv_event_t * e); // name: Standby
// extern void ui_event_uic_clk_clicked(lv_event_t * e); // name: Delete
// extern void ui_event_uic_clk_long_pressed(lv_event_t * e); // name: Clock
extern void ui_event_uic_clk_handler(lv_event_t * e); // name: Clock/Delete
extern void ui_event_uic_one_clicked(lv_event_t * e); // name: 1
extern void ui_event_uic_two_clicked(lv_event_t * e); // name: 2
extern void ui_event_uic_three_clicked(lv_event_t * e); // name: 3
extern void ui_event_uic_timer_clicked(lv_event_t * e); //name: name: Timer/Insert
extern void ui_event_uic_four_clicked(lv_event_t * e); //name: 4
extern void ui_event_uic_five_clicked(lv_event_t * e); //name: 5
extern void ui_event_uic_six_clicked(lv_event_t * e); //name: 6
extern void ui_event_uic_edit_clicked(lv_event_t * e); //name: Edit
extern void ui_event_uic_seven_clicked(lv_event_t * e); //name: 7
extern void ui_event_uic_eight_clicked(lv_event_t * e); //name: 8
extern void ui_event_uic_nine_clicked(lv_event_t * e); //name: 9
extern void ui_event_uic_yes_clicked(lv_event_t * e); //name: Yes/Enter
extern void ui_event_uic_mode_clicked(lv_event_t * e); //name: Mode
extern void ui_event_uic_z_ten_clicked(lv_event_t * e); //name: 0/10
extern void ui_event_uic_more_ten_clicked(lv_event_t * e); //name: >10
extern void ui_event_uic_no_clicked(lv_event_t * e); //name: No/Cancel

// SCREEN: ui_Screen2
extern void ui_event_uic_md_pl_clicked(lv_event_t * e); //name: ⏯ MD
extern void ui_event_uic_bkw_clicked(lv_event_t * e); //name: ⏪ Track Left
extern void ui_event_uic_frwd_clicked(lv_event_t * e); //name: ⏩ Track Right
extern void ui_event_uic_cd_pl_clicked(lv_event_t * e); //name: ⏯ CD
extern void ui_event_uic_stop_clicked(lv_event_t * e); //name: ⏹ Stop
extern void ui_event_uic_ntwk_clicked(lv_event_t * e); //name: Network
extern void ui_event_uic_grp_mode_clicked(lv_event_t * e); //name: Group Mode
extern void ui_event_uic_grp_min_clicked(lv_event_t * e); //name: Group -
extern void ui_event_uic_grp_plus_clicked(lv_event_t * e); //name: Group +
extern void ui_event_uic_mtrx_sur_clicked(lv_event_t * e); //name: Matrix Surround
extern void ui_event_uic_rec_mode_clicked(lv_event_t * e); //name: REC Mode
extern void ui_event_uic_spd_norm_clicked(lv_event_t * e); //name: REC Speed Norm
extern void ui_event_uic_spd_high_clicked(lv_event_t * e); //name: REC Speed High
extern void ui_event_uic_snd_clicked(lv_event_t * e); //name: Sound
extern void ui_event_uic_resume_clicked(lv_event_t * e); //name: Resume
extern void ui_event_uic_dspl_clicked(lv_event_t * e); //name: Display
extern void ui_event_uic_vol_minus_clicked(lv_event_t * e); //name: VOL -
extern void ui_event_uic_vol_plus_clicked(lv_event_t * e); //name: VOL +
extern void ui_event_uic_servmenu_clicked(lv_event_t * e); //name: Service menu

// SCREEN: ui_Screen3
extern void ui_event_uic_sm_clicked(lv_event_t * e); //name: Service menu
extern void ui_event_uic_ta_clicked(lv_event_t * e); //name: TempAdjust

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
