// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "lvgl.h" // For LV_LOG_USER, if send_ir_code is moved outside main.cpp and needs it

// Declarations for the IR sending functions defined in main.cpp
extern void send_sirc15_command(uint32_t device_address_8bit, uint32_t command_code_7bit);

// --- Screen 1 Event Handlers ---
void ui_event_uic_IO_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_IO clicked");
        send_sirc15_command(0xa8, 0x22); // POWER (I/O)
    }
}

void ui_event_uic_cd_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_cd clicked");
        send_sirc15_command(0x68, 0x26); // CD Eject
    }
}

void ui_event_uic_md_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_md clicked");
        send_sirc15_command(0x92, 0x26); // MD Eject
    }
}

void ui_event_uic_fn_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_fn clicked");
        send_sirc15_command(0xe2, 0x22); // FUNCTION (switch between MD, CD, Network)
    }
}

void ui_event_uic_slp_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_slp clicked");
        send_sirc15_command(0x06, 0x22); // SLEEP
    }
}

void ui_event_uic_stby_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_stby clicked");
        send_sirc15_command(0x86, 0x22); // Standby (First need set clock)
    }
}

// void ui_event_uic_clk_clicked(lv_event_t * e) {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         LV_LOG_USER("uic_clk clicked");
//         send_sirc15_command(0xc6, 0x22); // Clock/Delete single press
//     }
// }

// void ui_event_uic_clk_long_pressed(lv_event_t * e) {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     if(event_code == LV_EVENT_LONG_PRESSED) {
//         LV_LOG_USER("uic_clk long_pressed");
//         send_sirc15_command(0xc6, 0x22); // Clock/Delete long pressed
//     }
// }

// Combined handler for uic_clk
void ui_event_uic_clk_handler(lv_event_t * e) {
    lv_event_code_t code = lv_event_get_code(e);
    switch (code) {
        case LV_EVENT_CLICKED:
            LV_LOG_USER("uic_clk clicked: Clock/Delete single press");
            send_sirc15_command(0xc6, 0x22); // Clock/Delete single press
            break;
        case LV_EVENT_LONG_PRESSED:
            LV_LOG_USER("uic_clk long_pressed: Clock/Delete long pressed");
            send_sirc15_command(0xc6, 0x22); // Clock/Delete long pressed
            break;
        default:
            break;
    }
}

void ui_event_uic_one_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_one clicked");
        send_sirc15_command(0x00, 0x26); // 1
    }
}

void ui_event_uic_two_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_two clicked");
        send_sirc15_command(0x80, 0x26); // 2
    }
}

void ui_event_uic_three_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_three clicked");
        send_sirc15_command(0x40, 0x26); // 3 
    }
}

void ui_event_uic_timer_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_timer clicked");
        send_sirc15_command(0x46, 0x22); // Timer/Insert
    }
}

void ui_event_uic_four_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_four clicked");
        send_sirc15_command(0xc0, 0x26); // 4
    }
}

void ui_event_uic_five_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_five clicked");
        send_sirc15_command(0x20, 0x26); // 5
    }
}

void ui_event_uic_six_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_six clicked");
        send_sirc15_command(0xa0, 0x26); // 6
    }
}

void ui_event_uic_edit_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_edit clicked");
        send_sirc15_command(0x72, 0x26); // Edit
    }
}

void ui_event_uic_seven_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_seven clicked");
        send_sirc15_command(0x60, 0x26); // 7 
    }
}

void ui_event_uic_eight_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_eight clicked");
        send_sirc15_command(0xe0, 0x26); // 8 
    }
}

void ui_event_uic_nine_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_nine clicked");
        send_sirc15_command(0x10, 0x26); // 9 ???????????
    }
}

void ui_event_uic_yes_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_yes clicked");
        send_sirc15_command(0x08, 0x26); // Yes/Enter ?
    }
}

void ui_event_uic_mode_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_mode clicked");
        send_sirc15_command(0x88, 0x22); // Mode
    }
}

void ui_event_uic_z_ten_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_z_ten clicked");
        send_sirc15_command(0x30, 0x26); // 0/10
    }
}

void ui_event_uic_more_ten_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_more_ten clicked");
        send_sirc15_command(0xb0, 0x26); // >10 ?????
    }
}

void ui_event_uic_no_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_no clicked");
        send_sirc15_command(0xf0, 0x26); // No/Cancel -------------------------------
    }
}

// --- Screen 2 Event Handlers ---
void ui_event_uic_md_pl_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_md_pl clicked");
        send_sirc15_command(0x52, 0x26); // ⏯ MD (Play/Pause MD)
    }
}

void ui_event_uic_bkw_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_bkw clicked");
        send_sirc15_command(0x0c, 0x26); // ⏪ Track Left
    }
}

void ui_event_uic_frwd_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_frwd clicked");
        send_sirc15_command(0x8c, 0x26); // ⏩ Track Right
    }
}

void ui_event_uic_cd_pl_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_cd_pl clicked");
        send_sirc15_command(0xcc, 0x26); // ⏯ CD (Play/Pause CD)
    }
}

void ui_event_uic_stop_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_stop clicked");
        send_sirc15_command(0x02, 0x26); // ⏹ Stop
    }
}

void ui_event_uic_ntwk_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_ntwk clicked");
        send_sirc15_command(0xc2, 0x22); // Network 
    }
}

void ui_event_uic_grp_mode_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_grp_mode clicked");
        send_sirc15_command(0x00, 0x53); // Group Mode ---------------------------------
    }
}

void ui_event_uic_grp_min_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_grp_min clicked");
        send_sirc15_command(0x00, 0x55); // Group -  ----------------------------------
    }
}

void ui_event_uic_grp_plus_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_grp_plus clicked");
        send_sirc15_command(0x00, 0x54); // Group +  ------------------------------------
    }
}

void ui_event_uic_mtrx_sur_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_mtrx_sur clicked");
        send_sirc15_command(0x54, 0x22); // Matrix Surround
    }
}

void ui_event_uic_rec_mode_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_rec_mode clicked");
        send_sirc15_command(0xD2, 0x26); // REC Mode
    }
}

void ui_event_uic_spd_norm_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_spd_norm clicked");
        send_sirc15_command(0x32, 0x26); // REC Speed Norm
    }
}

void ui_event_uic_spd_high_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_spd_high clicked");
        send_sirc15_command(0xb2, 0x26); // REC Speed High
    }
}

void ui_event_uic_snd_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_snd clicked");
        send_sirc15_command(0x0c, 0x22); // Sound
    }
}

void ui_event_uic_resume_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_resume clicked");
        send_sirc15_command(0x82, 0x26); // Resume
    }
}

void ui_event_uic_dspl_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_dspl clicked");
        send_sirc15_command(0x38, 0x22); // Display
    }
}

void ui_event_uic_vol_minus_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_vol_minus clicked");
        send_sirc15_command(0xc8, 0x22); // VOL -
    }
}

void ui_event_uic_vol_plus_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_vol_plus clicked");
        send_sirc15_command(0x48, 0x22); // VOL +
    }
}
void ui_event_uic_sm_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_sm clicked");
        send_sirc15_command(0xbe, 0x22); // Service menu!!!!!
    }
}
void ui_event_uic_ta_clicked(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        LV_LOG_USER("uic_ta clicked");
        send_sirc15_command(0x7e, 0x26); // Temp Adjust!!!!!
    }
}
