// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_no;
lv_obj_t * uic_more_ten;
lv_obj_t * uic_z_ten;
lv_obj_t * uic_mode;
lv_obj_t * uic_yes;
lv_obj_t * uic_nine;
lv_obj_t * uic_eight;
lv_obj_t * uic_seven;
lv_obj_t * uic_edit;
lv_obj_t * uic_six;
lv_obj_t * uic_five;
lv_obj_t * uic_four;
lv_obj_t * uic_timer;
lv_obj_t * uic_three;
lv_obj_t * uic_two;
lv_obj_t * uic_one;
lv_obj_t * uic_clk;
lv_obj_t * uic_stby;
lv_obj_t * uic_slp;
lv_obj_t * uic_fn;
lv_obj_t * uic_md;
lv_obj_t * uic_cd;
lv_obj_t * uic_IO;
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Button2;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Panel16;
lv_obj_t * ui_Panel17;
lv_obj_t * ui_Panel18;
lv_obj_t * ui_Panel19;
lv_obj_t * ui_Panel20;
lv_obj_t * ui_Panel21;
lv_obj_t * ui_Panel22;
lv_obj_t * ui_Panel23;

// event funtions
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_screenshot_50_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 314
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 417
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, 30);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 144);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 77);
    lv_obj_set_y(ui_Button2, -210);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x144D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button2, lv_color_hex(0x0A2B0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button2, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Button2, lv_color_hex(0x04D03F), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Button2, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Button2, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 40);
    lv_obj_set_height(ui_Panel2, 40);
    lv_obj_set_x(ui_Panel2, 108);
    lv_obj_set_y(ui_Panel2, -135);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel2, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x016C13), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel2, 100, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel2, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel2, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel2, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 40);
    lv_obj_set_height(ui_Panel1, 40);
    lv_obj_set_x(ui_Panel1, -108);
    lv_obj_set_y(ui_Panel1, -135);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x0581E6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel1, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel1, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel1, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 40);
    lv_obj_set_height(ui_Panel3, 40);
    lv_obj_set_x(ui_Panel3, -36);
    lv_obj_set_y(ui_Panel3, -135);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel3, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel3, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel3, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel3, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel3, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 40);
    lv_obj_set_height(ui_Panel4, 40);
    lv_obj_set_x(ui_Panel4, -107);
    lv_obj_set_y(ui_Panel4, -67);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel4, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel4, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel4, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel4, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel5 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel5, 40);
    lv_obj_set_height(ui_Panel5, 40);
    lv_obj_set_x(ui_Panel5, -36);
    lv_obj_set_y(ui_Panel5, -67);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel5, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel5, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel5, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel5, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel5, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel6, 40);
    lv_obj_set_height(ui_Panel6, 40);
    lv_obj_set_x(ui_Panel6, 36);
    lv_obj_set_y(ui_Panel6, -68);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel6, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel6, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel6, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel6, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel7 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel7, 40);
    lv_obj_set_height(ui_Panel7, 40);
    lv_obj_set_x(ui_Panel7, 109);
    lv_obj_set_y(ui_Panel7, -67);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel7, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel7, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel7, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel7, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel7, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel8 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel8, 40);
    lv_obj_set_height(ui_Panel8, 40);
    lv_obj_set_x(ui_Panel8, -107);
    lv_obj_set_y(ui_Panel8, 1);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel8, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel8, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel8, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel8, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel8, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel8, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel9 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel9, 40);
    lv_obj_set_height(ui_Panel9, 40);
    lv_obj_set_x(ui_Panel9, -35);
    lv_obj_set_y(ui_Panel9, 1);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel9, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel9, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel9, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel9, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel9, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel9, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel10 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel10, 40);
    lv_obj_set_height(ui_Panel10, 40);
    lv_obj_set_x(ui_Panel10, 36);
    lv_obj_set_y(ui_Panel10, 1);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel10, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel10, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel10, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel10, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel10, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel10, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel10, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel11 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel11, 40);
    lv_obj_set_height(ui_Panel11, 40);
    lv_obj_set_x(ui_Panel11, 108);
    lv_obj_set_y(ui_Panel11, 1);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel11, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel11, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel11, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel11, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel11, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel11, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel12 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel12, 40);
    lv_obj_set_height(ui_Panel12, 40);
    lv_obj_set_x(ui_Panel12, -107);
    lv_obj_set_y(ui_Panel12, 69);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel12, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel12, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel12, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel12, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel12, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel12, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel12, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel13 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel13, 40);
    lv_obj_set_height(ui_Panel13, 40);
    lv_obj_set_x(ui_Panel13, -35);
    lv_obj_set_y(ui_Panel13, 69);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel13, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel13, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel13, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel13, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel13, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel13, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel13, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel14 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel14, 40);
    lv_obj_set_height(ui_Panel14, 40);
    lv_obj_set_x(ui_Panel14, 37);
    lv_obj_set_y(ui_Panel14, 69);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel14, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel14, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel14, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel14, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel14, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel14, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel14, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel15 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel15, 40);
    lv_obj_set_height(ui_Panel15, 40);
    lv_obj_set_x(ui_Panel15, 109);
    lv_obj_set_y(ui_Panel15, 69);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel15, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel15, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel15, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel15, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel15, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel15, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel16 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel16, 40);
    lv_obj_set_height(ui_Panel16, 40);
    lv_obj_set_x(ui_Panel16, -107);
    lv_obj_set_y(ui_Panel16, 138);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel16, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel16, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel16, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel16, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel16, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel16, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel16, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel17 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel17, 40);
    lv_obj_set_height(ui_Panel17, 40);
    lv_obj_set_x(ui_Panel17, -35);
    lv_obj_set_y(ui_Panel17, 138);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel17, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel17, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel17, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel17, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel17, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel17, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel17, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel18 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel18, 40);
    lv_obj_set_height(ui_Panel18, 40);
    lv_obj_set_x(ui_Panel18, 37);
    lv_obj_set_y(ui_Panel18, 137);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel18, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel18, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel18, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel18, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel18, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel18, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel18, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel19 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel19, 40);
    lv_obj_set_height(ui_Panel19, 40);
    lv_obj_set_x(ui_Panel19, 108);
    lv_obj_set_y(ui_Panel19, 137);
    lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel19, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel19, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel19, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel19, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel19, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel19, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel19, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel20 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel20, 40);
    lv_obj_set_height(ui_Panel20, 40);
    lv_obj_set_x(ui_Panel20, -107);
    lv_obj_set_y(ui_Panel20, 206);
    lv_obj_set_align(ui_Panel20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel20, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel20, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel20, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel20, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel20, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel20, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel20, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel21 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel21, 40);
    lv_obj_set_height(ui_Panel21, 40);
    lv_obj_set_x(ui_Panel21, -35);
    lv_obj_set_y(ui_Panel21, 206);
    lv_obj_set_align(ui_Panel21, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel21, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel21, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel21, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel21, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel21, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel21, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel21, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel21, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel21, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel21, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel21, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel22 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel22, 40);
    lv_obj_set_height(ui_Panel22, 40);
    lv_obj_set_x(ui_Panel22, 37);
    lv_obj_set_y(ui_Panel22, 206);
    lv_obj_set_align(ui_Panel22, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel22, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel22, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel22, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel22, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel22, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel22, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel22, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel22, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel22, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel22, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel22, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel23 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel23, 40);
    lv_obj_set_height(ui_Panel23, 40);
    lv_obj_set_x(ui_Panel23, 109);
    lv_obj_set_y(ui_Panel23, 206);
    lv_obj_set_align(ui_Panel23, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel23, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel23, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel23, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel23, lv_color_hex(0x0462AF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel23, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_Panel23, lv_color_hex(0x03F636), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_Panel23, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Panel23, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Panel23, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Panel23, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_Panel23, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    uic_IO = ui_Panel2;
    uic_cd = ui_Panel1;
    uic_md = ui_Panel3;
    uic_fn = ui_Panel4;
    uic_slp = ui_Panel5;
    uic_stby = ui_Panel6;
    uic_clk = ui_Panel7;
    uic_one = ui_Panel8;
    uic_two = ui_Panel9;
    uic_three = ui_Panel10;
    uic_timer = ui_Panel11;
    uic_four = ui_Panel12;
    uic_five = ui_Panel13;
    uic_six = ui_Panel14;
    uic_edit = ui_Panel15;
    uic_seven = ui_Panel16;
    uic_eight = ui_Panel17;
    uic_nine = ui_Panel18;
    uic_yes = ui_Panel19;
    uic_mode = ui_Panel20;
    uic_z_ten = ui_Panel21;
    uic_more_ten = ui_Panel22;
    uic_no = ui_Panel23;

    // Add event callbacks for Screen1 custom buttons
    lv_obj_add_event_cb(uic_IO, ui_event_uic_IO_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_cd, ui_event_uic_cd_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_md, ui_event_uic_md_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_fn, ui_event_uic_fn_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_slp, ui_event_uic_slp_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_stby, ui_event_uic_stby_clicked, LV_EVENT_CLICKED, NULL);
    // lv_obj_add_event_cb(uic_clk, ui_event_uic_clk_long_pressed, LV_EVENT_LONG_PRESSED, NULL);
    // lv_obj_add_event_cb(uic_clk, ui_event_uic_clk_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_clk, ui_event_uic_clk_handler, LV_EVENT_ALL, NULL); // Use combined handler
    lv_obj_add_event_cb(uic_one, ui_event_uic_one_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_two, ui_event_uic_two_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_three, ui_event_uic_three_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_timer, ui_event_uic_timer_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_four, ui_event_uic_four_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_five, ui_event_uic_five_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_six, ui_event_uic_six_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_edit, ui_event_uic_edit_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_seven, ui_event_uic_seven_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_eight, ui_event_uic_eight_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_nine, ui_event_uic_nine_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_yes, ui_event_uic_yes_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_mode, ui_event_uic_mode_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_z_ten, ui_event_uic_z_ten_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_more_ten, ui_event_uic_more_ten_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(uic_no, ui_event_uic_no_clicked, LV_EVENT_CLICKED, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image1 = NULL;
    ui_Button2 = NULL;
    uic_IO = NULL;
    ui_Panel2 = NULL;
    uic_cd = NULL;
    ui_Panel1 = NULL;
    uic_md = NULL;
    ui_Panel3 = NULL;
    uic_fn = NULL;
    ui_Panel4 = NULL;
    uic_slp = NULL;
    ui_Panel5 = NULL;
    uic_stby = NULL;
    ui_Panel6 = NULL;
    uic_clk = NULL;
    ui_Panel7 = NULL;
    uic_one = NULL;
    ui_Panel8 = NULL;
    uic_two = NULL;
    ui_Panel9 = NULL;
    uic_three = NULL;
    ui_Panel10 = NULL;
    uic_timer = NULL;
    ui_Panel11 = NULL;
    uic_four = NULL;
    ui_Panel12 = NULL;
    uic_five = NULL;
    ui_Panel13 = NULL;
    uic_six = NULL;
    ui_Panel14 = NULL;
    uic_edit = NULL;
    ui_Panel15 = NULL;
    uic_seven = NULL;
    ui_Panel16 = NULL;
    uic_eight = NULL;
    ui_Panel17 = NULL;
    uic_nine = NULL;
    ui_Panel18 = NULL;
    uic_yes = NULL;
    ui_Panel19 = NULL;
    uic_mode = NULL;
    ui_Panel20 = NULL;
    uic_z_ten = NULL;
    ui_Panel21 = NULL;
    uic_more_ten = NULL;
    ui_Panel22 = NULL;
    uic_no = NULL;
    ui_Panel23 = NULL;

}
