// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image5;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Panel25;
extern lv_obj_t * ui_Panel24;
extern lv_obj_t * ui_Panel26;
extern lv_obj_t * ui_Panel27;
extern lv_obj_t * ui_Panel28;
extern lv_obj_t * ui_Panel29;
extern lv_obj_t * ui_Panel30;
extern lv_obj_t * ui_Panel31;
extern lv_obj_t * ui_Panel32;
extern lv_obj_t * ui_Panel33;
extern lv_obj_t * ui_Panel34;
extern lv_obj_t * ui_Panel35;
extern lv_obj_t * ui_Panel36;
extern lv_obj_t * ui_Panel37;
extern lv_obj_t * ui_Panel38;
extern lv_obj_t * ui_Panel39;
extern lv_obj_t * ui_Panel41;
extern lv_obj_t * ui_Panel40;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_md_pl;
extern lv_obj_t * uic_bkw;
extern lv_obj_t * uic_frwd;
extern lv_obj_t * uic_cd_pl;
extern lv_obj_t * uic_stop;
extern lv_obj_t * uic_ntwk;
extern lv_obj_t * uic_grp_mode;
extern lv_obj_t * uic_grp_min;
extern lv_obj_t * uic_grp_plus;
extern lv_obj_t * uic_mtrx_sur;
extern lv_obj_t * uic_rec_mode;
extern lv_obj_t * uic_spd_norm;
extern lv_obj_t * uic_spd_high;
extern lv_obj_t * uic_snd;
extern lv_obj_t * uic_resume;
extern lv_obj_t * uic_dspl;
extern lv_obj_t * uic_vol_minus;
extern lv_obj_t * uic_vol_plus;
extern lv_obj_t * uic_servmenu;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

