// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_Panel23;
// CUSTOM VARIABLES
extern lv_obj_t * uic_IO;
extern lv_obj_t * uic_cd;
extern lv_obj_t * uic_md;
extern lv_obj_t * uic_fn;
extern lv_obj_t * uic_slp;
extern lv_obj_t * uic_stby;
extern lv_obj_t * uic_clk;
extern lv_obj_t * uic_one;
extern lv_obj_t * uic_two;
extern lv_obj_t * uic_three;
extern lv_obj_t * uic_timer;
extern lv_obj_t * uic_four;
extern lv_obj_t * uic_five;
extern lv_obj_t * uic_six;
extern lv_obj_t * uic_edit;
extern lv_obj_t * uic_seven;
extern lv_obj_t * uic_eight;
extern lv_obj_t * uic_nine;
extern lv_obj_t * uic_yes;
extern lv_obj_t * uic_mode;
extern lv_obj_t * uic_z_ten;
extern lv_obj_t * uic_more_ten;
extern lv_obj_t * uic_no;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

